# Pytorch Fundamental

In [2]:
# importing pytorch
import torch
torch.__version__

'2.3.1'

## Introduction to Tensor

In [5]:
# creating tensor
scalar = torch.tensor(10)
scalar

tensor(10)

In [6]:
# check dimension of tensor
scalar.ndim

0

In [7]:
# retrieve the number from the tensor
scalar.item()

10

In [14]:
# creating a vector
vector = torch.tensor([8,8])
vector

tensor([8, 8])

In [15]:
# dimensions of vector
vector.ndim

1

In [16]:
# check vector shape
vector.shape

torch.Size([2])

In [17]:
# creating a matrix
MATRIX = torch.tensor([[7,8], 
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX.ndim

2

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [21]:
# create a tensor
TENSOR = torch.tensor([[[1,2,3],
                       [7,8,9],
                       [4,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [7, 8, 9],
         [4, 5, 6]]])

In [22]:
TENSOR.ndim

3

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])

In [24]:
# create a random tensor
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.3991, 0.0153, 0.1536, 0.1562],
        [0.6503, 0.5978, 0.1630, 0.0391],
        [0.0257, 0.3568, 0.0292, 0.3818]])

In [26]:
random_tensor.ndim

2

In [27]:
random_tensor.shape

torch.Size([3, 4])

In [28]:
# create a zeros tensor
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
zeros.ndim

2

In [30]:
zeros.shape

torch.Size([3, 4])

In [31]:
# create a ones tensor
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
ones.shape

torch.Size([3, 4])

In [33]:
ones.ndim

2

In [34]:
# create a tensor with range
zero_to_ten = torch.arange(start = 1, end = 10, step=1)
zero_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
zero_to_ten.ndim

1

In [36]:
zero_to_ten.shape

torch.Size([9])

In [37]:
# default data type for tensor
# Default datatype is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, 
                               device=None,
                               requires_grad=False)  

float_32_tensor.shape

torch.Size([3])

In [38]:
float_32_tensor.dtype

torch.float32

In [39]:
float_32_tensor.device

device(type='cpu')

## Getting information from tensor

In [42]:
x_tensor = torch.rand(3,4)
print(x_tensor)
print(f"Shape of tensor: {x_tensor.shape}")
print(f"Datatype of tensor: {x_tensor.dtype}")
print(f"Device of tensor: {x_tensor.device}")

tensor([[0.4219, 0.5441, 0.1155, 0.6845],
        [0.4892, 0.1447, 0.4015, 0.7021],
        [0.4042, 0.1543, 0.2472, 0.8095]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: cpu


## Tensor Operations

In [43]:
tensor = torch.tensor([1,5,9])
tensor

tensor([1, 5, 9])

In [45]:
# Addition
tensor+10

tensor([11, 15, 19])

In [46]:
# Multiplication
tensor * 2

tensor([ 2, 10, 18])

In [47]:
# subtract
tensor - 2

tensor([-1,  3,  7])

In [48]:
# Tensors don't change unless reassigned
tensor

tensor([1, 5, 9])

In [49]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -5, -1])

In [51]:
# Can also use torch functions
tensor = torch.tensor([2,4,6])
torch.multiply(tensor, 10)

tensor([20, 40, 60])

In [52]:
# Original tensor is still unchanged 
tensor

tensor([2, 4, 6])

In [53]:
# Element-wise multiplication 
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([2, 4, 6]) * tensor([2, 4, 6])
Equals: tensor([ 4, 16, 36])


## Matrix Multiplication

In [54]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [56]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [57]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [58]:
# Can also use the "@" symbol for matrix multiplication,\
tensor @ tensor

tensor(14)

## Most common errors in deep learning (shape errors)

In [59]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [60]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

## Finding the min, max, mean, sum, etc (aggregation)

In [61]:
x = torch.arange(0, 50, 5)
x

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [63]:
print(f"Minimum : {x.min()}")
print(f"Maximum : {x.max()}")
print(f"Sum : {x.sum()}")
print(f"Mean : {x.type(torch.float32).mean()}")

Minimum : 0
Maximum : 45
Sum : 225
Mean : 22.5


In [65]:
# Positional min/max
print(f"Index of Minimum value : {x.argmin()}")
print(f"Index of Maximum value: {x.argmax()}")

Index of Minimum value : 0
Index of Maximum value: 9


## Change tensor datatype

In [66]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [67]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [68]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

## Indexing (selecting data from tensors)

In [69]:
num = torch.arange(1,10)
num

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
# reshape and assign
num = num.reshape(1,3,3)

In [79]:
# Let's index bracket by bracket
print(f"First square bracket:\n{num[0]}") 
print(f"Second square bracket: {num[0][0]}") 
print(f"Third square bracket: {num[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [80]:
# Get all values of 0th dimension and the 0 index of 1st dimension
num[:, 0]

tensor([[1, 2, 3]])

In [82]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
num[:, :, 1]

tensor([[2, 5, 8]])

In [83]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
num[:, 1, 1]

tensor([5])

In [85]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
num[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

In [86]:
# NumPy array to tensor
import numpy as np
array = np.arange(1.0, 10.0)
tensor = torch.from_numpy(array)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [87]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [88]:
# Tensor to NumPy array
tensor = torch.ones(10) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [89]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))